name: Simple Logger

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  simple_log:
    runs-on: ubuntu-latest
    steps:
      - name: Log event
        run: |
          echo "Event triggered at $(date)"
          echo "Event data: ${{ toJson(github) }}"
