name: Capture Copilot Data
on:
  repository_dispatch:
    types: [data-capture]

jobs:
  log_request:
    runs-on: ubuntu-latest
    steps:
      - name: Print event payload
        run: echo "Received payload: ${{ toJson(github.event.client_payload) }}"
