name: Capture Copilot Data
on:
  workflow_dispatch:
  push:
  repository_dispatch:
    types: [copilot-badge]

jobs:
  log_copilot_request:
    runs-on: ubuntu-latest
    steps:
      - name: Log GET Request
        run: echo "Copilot acessou o badge em $(date)"
